import { Injectable } from '@angular/core';

export interface Product {
  id: string;
  description: string;
  price: number;
  imageUrl: string;
  stock: number;
  createdAt: string;
  updatedAt: string;
  category?: string;
  isLimited: boolean;
  isNew: boolean;
  slug?: string;
  title?: string;
}

@Injectable({ providedIn: 'root' })
export class ProductService {
  private products: Product[] = [
    {
      id: '1',
      title: 'Dank Shades',
      description: 'Stylish sunglasses with UV protection',
      price: 29.99,
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
      stock: 50,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Sunglasses',
      isLimited: false,
      isNew: true,
      slug: 'dank-shades',
    },
    {
      id: '2',
      title: 'Meme Goggles',
      description: 'Fun and quirky eyewear for the modern age',
      price: 24.99,
      imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
      stock: 30,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Sunglasses',
      isLimited: false,
      isNew: false,
      slug: 'meme-goggles',
    },
    {
      id: '3',
      title: 'Dutch Flex',
      description: 'Premium reading glasses with flexible frames',
      price: 34.99,
      imageUrl: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
      stock: 25,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Eyeglasses',
      isLimited: true,
      isNew: false,
      slug: 'dutch-flex',
    },
    {
      id: '4',
      title: 'Cyber Vision',
      description: 'Futuristic blue-tint sunglasses for the bold.',
      price: 39.99,
      imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
      stock: 15,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Sunglasses',
      isLimited: true,
      isNew: true,
      slug: 'cyber-vision',
    },
    {
      id: '5',
      title: 'Retro Roundz',
      description: 'Classic round frames with a meme twist.',
      price: 19.99,
      imageUrl: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=400&q=80',
      stock: 40,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Eyeglasses',
      isLimited: false,
      isNew: true,
      slug: 'retro-roundz',
    },
    {
      id: '6',
      title: 'Flexi Meme',
      description: 'Flexible frames for maximum comfort and style.',
      price: 27.99,
      imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=400&q=80',
      stock: 22,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Eyeglasses',
      isLimited: false,
      isNew: false,
      slug: 'flexi-meme',
    },
    {
      id: '7',
      title: 'Stealth Blackout',
      description: 'Matte black shades for the ultimate meme lord.',
      price: 44.99,
      imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=400&q=80',
      stock: 10,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Sunglasses',
      isLimited: true,
      isNew: false,
      slug: 'stealth-blackout',
    },
    {
      id: '8',
      title: 'Hype Beast',
      description: 'Limited drop, neon-accented frames for hypebeasts.',
      price: 59.99,
      imageUrl: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
      stock: 5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Sunglasses',
      isLimited: true,
      isNew: true,
      slug: 'hype-beast',
    },
    {
      id: '9',
      title: 'Pixel Vision',
      description: 'Blocky, pixel-art inspired glasses for gamers.',
      price: 21.99,
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
      stock: 18,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Accessories',
      isLimited: false,
      isNew: false,
      slug: 'pixel-vision',
    },
    {
      id: '10',
      title: 'Meme Shield',
      description: 'Oversized shield sunglasses for max meme protection.',
      price: 49.99,
      imageUrl: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80',
      stock: 8,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Sunglasses',
      isLimited: true,
      isNew: false,
      slug: 'meme-shield',
    },
    {
      id: '11',
      title: 'Glitch Frame',
      description: 'Frames with a digital glitch pattern, limited edition.',
      price: 54.99,
      imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=400&q=80',
      stock: 12,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Eyeglasses',
      isLimited: true,
      isNew: true,
      slug: 'glitch-frame',
    },
    {
      id: '12',
      title: 'Vaporwave Dream',
      description: 'Pastel-tinted glasses for vaporwave fans.',
      price: 32.99,
      imageUrl: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=400&q=80',
      stock: 20,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Accessories',
      isLimited: false,
      isNew: true,
      slug: 'vaporwave-dream',
    },
    {
      id: '13',
      title: 'Neon Nights',
      description: 'Glow-in-the-dark frames for night owls.',
      price: 37.99,
      imageUrl: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=400&q=80',
      stock: 14,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Accessories',
      isLimited: true,
      isNew: false,
      slug: 'neon-nights',
    },
    {
      id: '14',
      title: 'Street Flex',
      description: 'Urban style, flexible frames for daily wear.',
      price: 29.99,
      imageUrl: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80',
      stock: 28,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Eyeglasses',
      isLimited: false,
      isNew: true,
      slug: 'street-flex',
    },
    {
      id: '15',
      title: 'Meme Aviator',
      description: 'Aviator style with a meme-worthy gold finish.',
      price: 42.99,
      imageUrl: 'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=400&q=80',
      stock: 16,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      category: 'Sunglasses',
      isLimited: false,
      isNew: false,
      slug: 'meme-aviator',
    },
  ];

  getProducts(): Product[] {
    return this.products;
  }

  getProductById(id: string): Product | undefined {
    return this.products.find(p => p.id === id);
  }
} 